-- 코드를 입력하세요
SELECT TITLE
       ,GB.BOARD_ID
       ,GR.REPLY_ID
       ,GR.WRITER_ID
       ,GR.CONTENTS
       ,DATE_FORMAT(GR.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD AS GB JOIN USED_GOODS_REPLY AS GR
ON GB.BOARD_ID = GR.BOARD_ID
WHERE GB.CREATED_DATE LIKE '2022-10%'
ORDER BY GR.CREATED_DATE ASC
        ,GB.TITLE ASC;